## Numpy Arrays
Always could refer the documentation of numpy for any assistance regarding how any function works

In [3]:
import numpy as np
a = np.array([1,2,3],dtype=float)
a

array([1., 2., 3.])

In [10]:
a = np.ones(5, dtype=int)
a
b = np.zeros(5,dtype=float)
b

array([0., 0., 0., 0., 0.])

In [14]:
a = np.full((5,3), 100.5)
a

array([[100.5, 100.5, 100.5],
       [100.5, 100.5, 100.5],
       [100.5, 100.5, 100.5],
       [100.5, 100.5, 100.5],
       [100.5, 100.5, 100.5]])

In [34]:
a = np.empty(5,dtype=float)
a

array([8.70892463e-153, 6.01346953e-154, 5.98179233e-154, 1.03063392e-113,
       1.05117820e-153])

In [37]:
a = np.arange(10)
print(a)
a = np.arange(2,10)
print(a)
a = np.arange(2,10,5,dtype=float)
a

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


array([2., 7.])

In [42]:
a = np.linspace(2,10,15)
print(a)
print(a[1]-a[0])
print(a[2]-a[1])

[ 2.          2.57142857  3.14285714  3.71428571  4.28571429  4.85714286
  5.42857143  6.          6.57142857  7.14285714  7.71428571  8.28571429
  8.85714286  9.42857143 10.        ]
0.5714285714285712
0.5714285714285716


In [43]:
a = np.identity(3)    #creates an identity matrix of n*n
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [67]:
a = np.random.randn(10)
print(a)
print(a.shape)
a = np.random.rand(10)*10
print(a)
a = np.random.randint(49,size=(3,4))
print(a)
print(a.shape)
np.random.randint(10, 4)

[ 0.53782681  0.87163572  0.23273026  1.21774695  0.76012067  0.35456727
 -1.45181524 -0.37059234 -2.24089586 -0.4804573 ]
(10,)
[8.04551366 4.4715936  0.62271455 5.91412985 7.91034904 1.91123798
 5.39060898 3.67021859 8.39945808 3.56831165]
[[17 12  0 24]
 [30 29 47 31]
 [43  0 27 29]]
(3, 4)


ValueError: low >= high

## Mathematical operations on numpy arrays

In [6]:
a = np.random.randint(0,5,5)
b = np.random.randint(5,10,5)

array([1, 3, 0, 0, 3])

In [8]:
print(a)
print(b)
b = a + b
c = a*b
d = a / b
e = a // b
f = a ** b
print(b)
print(c)
print(d)
print(e)
print(f)

[1 3 0 0 3]
[ 9 11  5  6  8]
[10 14  5  6 11]
[10 42  0  0 33]
[0.1        0.21428571 0.         0.         0.27272727]
[0 0 0 0 0]
[      1 4782969       0       0  177147]


In [10]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())

7
1.4
0
3
2
1


In [11]:
print(a>b)
print(a==b)
print(a!=b)

[False False False False False]
[False False False False False]
[ True  True  True  True  True]


In [13]:
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a))

[False False False False False]
[ True  True  True  True  True]
[False False  True  True False]


## Boolean Indexing

In [16]:
a = np.array([1,5,8, 15, 105,26])
print(a)
print(a[a>5])
print(a[(a>5) & (a<100)])

[  1   5   8  15 105  26]
[  8  15 105  26]
[ 8 15 26]


In [18]:
a[:3]=100
a

array([100, 100, 100,  15, 105,  26])

In [20]:
a[a==100]=5
a

array([  5,   5,   5,  15, 105,  26])

In [29]:
ind = np.where(a==5)
print(ind)
b = np.array([10,25,98,47,55])
print(b[ind])
print(a)
a=-a
a

(array([0, 1, 2], dtype=int64),)
[10 25 98]
[  5   5   5  15 105  26]


array([  -5,   -5,   -5,  -15, -105,  -26])

In [31]:
b[ind]=-b[ind]
b

array([-10, -25, -98,  47,  55])

In [32]:
b = np.random.randint(1,10,(3,3))
print(b)

[[5 9 9]
 [8 4 8]
 [9 7 8]]


In [37]:
bool_arr = b[:,1]>5
print(bool_arr)
b[bool_arr,1]=10
b

[ True False  True]


array([[ 5, 10,  9],
       [ 8,  4,  8],
       [ 9, 10,  8]])

## Broadcasting

In [43]:
## Rules of compatability
## 1) If the all the dimensions are same example 3,4 is comptabile with 3,4
## 2) If any one of the dimension is one example 3,5 is compatible with 1,5 here broadcasting takes place

a = np.random.randint(1,10,(3,5))
b = np.random.randint(1,10,(5))
c = np.random.randint(1,10,(5,3))
print(a)
print(b)
print(c)
print(a.shape,b.shape,c.shape)

[[5 5 4 5 3]
 [1 7 2 3 7]
 [5 1 8 8 2]]
[4 2 8 3 6]
[[4 1 5]
 [7 3 6]
 [6 7 9]
 [4 7 1]
 [2 3 4]]
(3, 5) (5,) (5, 3)


In [52]:
d = a+b
print(d)
#ans = a+c  # This gives error
#print(ans)
c = np.transpose(c)
print(a.shape,c.shape)
ans = a + c
print(ans)

[[ 9  7 12  8  9]
 [ 5  9 10  6 13]
 [ 9  3 16 11  8]]
(3, 5) (3, 5)
[[ 9 12 10  9  5]
 [ 2 10  9 10 10]
 [10  7 17  9  6]]
